# Site settings
title: JDStraughan
email: jdstraughan@gmail.com
description: "Blog of Web Developer, Entrepreneur, and Disneyphile Jason D. Straughan. Founder and CEO of Grok Interactive and Co-Founder of Codeup."
url: "http://jdstraughan.com"
twitter_username: jdstraughan
github_username:  JDStraughan
facebook_username:  JDStraughan
linkedin_username:  JDStraughan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title
paginate: 6
exclude: ["node_modules"]

gems:
  - jekyll-paginate

# Compress HTML settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: [local]
