# Site settings
title: JDStraughan
email: jdstraughan@gmail.com
description: "Blog of San Antonio Web Developer, Rubyist, and Entrepreneur Jason D. Straughan"
url: "http://jdstraughan.com"
twitter_username: JDStraughan
github_username:  JDStraughan
facebook_username:  JDStraughan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title
paginate: 6
exclude: ["node_modules"]
