auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]

paginate: 10 //the number of posts per page

tag_page_layout: tag_page
tag_page_dir: tag
source: ./_source
plugins: ./_source/_plugins
